### ISSUE TITLE
python for ... 

### ISSUE THREAD

**Issue by Xoristzatziki** [pythonnet/pythonnet.github.io#13]
«Python for .NET» It is a little bit confusing. Searching for a way to use python in .NET "solutions" drops people here. But the fact is that this project is the other way. Is about bringing the .NET to python. In MHO a much more clear approach could be ex. «.NET in Python».

**Comment by filmor** [comment]
It's the kind of established name for the project, though. And ".NET in Python" doesn't quite catch it either as you can use it to embed CPython into .NET as well. It works both ways. We could think about changing the references to `pythonnet`, as the package is named.
